MvcPresentation/Controllers/TransportationController.cs
using DataObjects;
using LogicLayer;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MvcPresentation.Controllers
{
    public class TransportationController : Controller
    {
        private MainManager _manager = MainManager.GetMainManager();

        // GET: Transportation
        public ActionResult Index(string searchText)
        {
            List<TransportationOrderVM> orders = new List<TransportationOrderVM>();

            try
            {
                if (!string.IsNullOrEmpty(searchText))
                {
                    orders = _manager.TransportationOrderManager.ViewAllTransportationOrders()
                                                                .Where(x => x.TransportItem.ToLower().Contains(searchText))
                                                                .ToList();
                }
                else
                {
                    orders = _manager.TransportationOrderManager.ViewAllTransportationOrders();
                } 
            }
            catch (Exception)
            {
                throw;
            }
           
            return View(orders);
        }

        // GET: Transportation/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Transportation/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Transportation/Create
        [HttpPost]
        public ActionResult Create(TransportationOrder order)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Transportation/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: Transportation/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, TransportationOrder order)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Transportation/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Transportation/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, TransportationOrder order)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

MvcPresentation/Views/Transportation/Index.cshtml
@*
    Creator: Liam Easton
    Created: ???
    Summary: Creation of the TransportationOrderVM index page
    Last Updated By: Liam Easton
    Last Updated: 4/19/2024
    What Was Changed: changed the add button and the table style
*@
@model IEnumerable<DataObjects.TransportationOrderVM>

@{
    ViewBag.Title = "Index";
    ViewBag.Hero = "Transporatation Orders";
}


<div class="d-flex pr-5 pt-3 table-header-filter">
    <div>
        <button class="btn-grey br-30 fs-5 p-2 px-3 grow" href="@Url.Action("Create", "Transporation")">
            Create Order
        </button>
    </div>
    <input id="searchBox" class="fs-5 p-2 px-3 mx-3" type="text" onkeyup="myFunction()" placeholder="Search for item...">
    <img onclick="searchForItem()" class="icon px-3 search-icon" src="~/Images/search.svg" />
</div>
<table class="table my-4">
    <tr class="bg-dark text-white">
        <th>
            @Html.DisplayNameFor(model => model.DayPosted)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.LineItemAmount)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.TransportItem)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DayToPickUp)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Fulfilled)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Vendor)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.city)
        </th>
        <th>
            Options
        </th>
    </tr>

    @foreach (var item in Model)
    {
        <tr style="background: #CFCECD!important" class="text-dark">
            <td>
                @item.DayPosted.ToShortDateString()
            </td>
            <td>
                @item.LineItemAmount.ToString("c")
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.TransportItem)
            </td>
            <td>
                @item.DayToPickUp.ToShortDateString()
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Fulfilled)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Vendor)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.city)
            </td>
            <td>
                @if (User.IsInRole("Admin"))
                {        
                    <a class="text-decoration-none text-dark" href="@Url.Action("Edit", "Transporation", new {  id = item.TransportItemID })">
                        Edit
                    </a>
                    <a class="text-decoration-none text-dark" href="@Url.Action("Delete", "Transporation", new {  id = item.TransportItemID })">
                        Delete
                    </a>
                }
                <a class="text-decoration-none text-dark" href="@Url.Action("Details", "Transporation", new {  id = item.TransportItemID })">
                    Details
                </a>
            </td>
        </tr>
    }

</table>
<script>
        function searchForItem() {
            var item = document.getElementById("searchBox").value.trim().toLowerCase();
            var indexURL = '@Url.Action("Index", "Transportation")' + '?searchText=' + encodeURIComponent(item);
            window.location.href = indexURL;
        };
</script>