MvcPresentation/Controllers/VisitationsController.cs
using DataObjects;
using LogicLayer;
using Microsoft.Ajax.Utilities;
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MvcPresentation.Controllers
{
    public class VisitationsController : Controller
    {
        private MainManager _manager = MainManager.GetMainManager();
        // GET: Visitations
        public ActionResult Index()
        {
            List<Visit> visits = new List<Visit>();

            try
            { 
                visits = _manager.VisitManager.SelectVisitWithFromTo(DateTime.Parse("1900-01-01"), DateTime.Now);
            }
            catch
            {

                throw;
            }

            return View(visits);
        }

        // GET: Visitations/Details/5
        public ActionResult Details(int id)
        {
            Visit visit = new Visit();

            try
            {
                visit = _manager.VisitManager.SelectVisitWithFromTo(DateTime.Parse("1900-01-01"), DateTime.Now)
                                              .FirstOrDefault(x => x.VisitID == id);
            }
            catch
            {
                throw;
            }

            return View(visit);
        }

        // GET: Visitations/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Visitations/Create
        [HttpPost]
        public ActionResult Create(Visit visit)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    _manager.VisitManager.CreateVisit(visit);
                    return RedirectToAction("Index");
                }
                else
                {
                    throw new Exception();
                }
            }
            catch
            {
                return View(visit);
            }
        }

        // GET: Visitations/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Visitations/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, Visit visit)
        {
            try
            {
                visit = _manager.VisitManager.GetVisitByVisitID(id);
                if(visit == null)
                {
                    return View("Error");
                }
                else
                {
                    _manager.VisitManager.DeleteVisit(visit);
                    return RedirectToAction("Index");
                }
            }
            catch(Exception ex)
            {
                return View(ex);
            }
        }


        [HttpPost]
        public ActionResult Reschedule(int id, Visit visit)
        {
            try
            {
                visit = _manager.VisitManager.GetVisitByVisitID(id);
                if (visit == null)
                {
                    return View("Error");
                }
                else
                {
                    _manager.VisitManager.DeleteVisit(visit);
                    return RedirectToAction("Create");
                }
            }
            catch (Exception ex)
            {
                return View(ex);
            }
        }
    }
}

MvcPresentation/Views/Visitations/Create.cshtml
@*
    Creator: Liam Easton
    Created: 3/20/2024
    Summary: Creation of the create actionlink
    Last Updated By: Liam Easton
    Last Updated: 3/20/2024
    What Was Changed: Added date inputs instead of text
    Last Updated By: Liam Easton
    Last Updated: 4/25/2024
    What Was Changed: Changed UI to look like other pages
*@
@model DataObjects.Visit

@{
    ViewBag.Title = "Create";
    ViewBag.Hero = "Create a new visit";
}


<div class="default-container">
    <div>
        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()
        <div class="form-horizontal">
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                First Name:
                <div class="col-md-10">
                    @Html.EditorFor(model => model.FirstName, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.FirstName, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                Last Name:
                <div class="col-md-10">
                    @Html.EditorFor(model => model.LastName, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.LastName, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                Check in:
                <div class="col-md-10">
                    @Html.TextBoxFor(model => model.CheckIn, "{0:yyyy-MM-dd}", new { @class = "form-control", type = "date" })
                    @Html.ValidationMessageFor(model => model.CheckIn, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                Check out:
                <div class="col-md-10">
                    @Html.TextBoxFor(model => model.CheckOut, "{0:yyyy-MM-dd}", new { @class = "form-control", type = "date" })
                    @Html.ValidationMessageFor(model => model.CheckOut, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                Reason for visiting:
                <div class="col-md-10">
                    @Html.EditorFor(model => model.VisitReason, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.VisitReason, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Create" class="btn-generic" />
                </div>
            </div>
        </div>
        }
    </div>
    <div>
        <div class="form-group mt-4">
            <button class="btn-generic" onclick="window.location.href='@Url.Action("Index", "Visitations")'">
                All Visitations
            </button>
        </div>
    </div>
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

MvcPresentation/Views/Visitations/Delete.cshtml
@*
    Creator: Liam Easton
    Created: 3/20/2024
    Summary: Creation of the delete actionlink
    Last Updated By: Liam Easton
    Last Updated: 3/20/2024
    What Was Changed: initial creation
*@
@model DataObjects.Visit

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Visit</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.FirstName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FirstName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LastName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LastName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CheckIn)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CheckIn)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CheckOut)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CheckOut)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.VisitReason)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.VisitReason)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Status)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Status)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.GetCheckIn)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.GetCheckIn)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.GetCheckOut)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.GetCheckOut)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.VisitStatus)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.VisitStatus)
        </dd>

    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

MvcPresentation/Views/Visitations/Details.cshtml
@*
    Creator: Liam Easton
    Created: 3/20/2024
    Summary: Creation of the details actionlink
    Last Updated By: Liam Easton
    Last Updated: 3/20/2024
    What Was Changed: initial creation
*@
@model DataObjects.Visit

@{
    ViewBag.Title = "Details";
    ViewBag.Hero = "Visit Details";
}

<div class="default-container">
    <div>
        <dl class="dl-horizontal">
            <dt>
                Visitor:
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Name)
            </dd>

            <dt>
                Check In:
            </dt>

            <dd>
                @Html.DisplayFor(model => model.GetCheckIn)
            </dd>

            <dt>
                Check Out:
            </dt>

            <dd>
                @Html.DisplayFor(model => model.GetCheckOut)
            </dd>

            <dt>
                Visit Reason:
            </dt>

            <dd>
                @Html.DisplayFor(model => model.VisitReason)
            </dd>
        </dl>
    </div>
    <div>
        <button class="my-4 btn-grey br-30 p-3 grow">
            <a class="text-decoration-none text-dark" onclick="window.location.href='@Url.Action("Index", "Visitations")'">
                All Visits
            </a>
        </button>
    </div>
    
</div>

MvcPresentation/Views/Visitations/Index.cshtml
@*
    Creator: Liam Easton
    Created: 3/15/2024
    Summary: Creation of the index actionlink
    Last Updated By: Liam Easton
    Last Updated: 3/15/2024
    What Was Changed: initial creation
    Last Updated By: Liam Easton
    Last Updated: 4/12/2024
    What Was Changed: initial creation
    Last Updated By: Liam Easton
    Last Updated: 4/19/2024
    What Was Changed: changed the add button and the table style
*@
@model IEnumerable<DataObjects.Visit>

@{
    ViewBag.Title = "Index";
    ViewBag.Hero = "All Visits";
}

@*delete modal*@
<div class="modal text-light" id="delete-modal" tabindex="-1" aria-labelledby="modal-title" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content bg-dark">
            <div class="modal-header">
                <h5 class="text-white modal-title delete-message" id="modal-title"></h5>
                <button type="button" class="btn-close bg-white" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-footer">
                @using (Html.BeginForm("Delete", "Visitations", FormMethod.Post))
                {
                    @Html.AntiForgeryToken()
                    <input type="hidden" id="delete-visit-id" name="id" value="" />

                    <div class="form-actions">
                        <input id="confirm-delete-button" type="submit" value="Delete" class="btn btn-danger" />
                    </div>
                }
            </div>
        </div>
    </div>
</div>

@*Reschedule modal*@
<div class="modal text-light" id="reschedule-modal" tabindex="-1" aria-labelledby="modal-title" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content bg-dark">
            <div class="modal-header">
                <h5 class="text-white modal-title reschedule-message" id="modal-title"></h5>
                <button type="button" class="btn-close bg-white" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-footer">
                @using (Html.BeginForm("Reschedule", "Visitations", FormMethod.Post))
                {
                    @Html.AntiForgeryToken()
                    <input type="hidden" id="reschedule-visit-id" name="id" value="" />

                    <div class="form-actions">
                        <input id="confirm-reschedule-button" type="submit" value="Reschedule" class="btn btn-secondary" />
                    </div>
                }
            </div>
        </div>
    </div>
</div>
<a class="btn-generic" href="@Url.Action("Create", "Visitations")">
    Create Visitation
</a>

@if (Model.Count() > 0)
{
    <table class="table my-4">
        <tr class="bg-dark text-white">
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CheckIn)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CheckOut)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.VisitReason)
            </th>
            <th>Options</th>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @item.CheckIn.ToString("MM/dd/yyyy hh:mm tt")
            </td>
            <td>
                @item.CheckOut.ToString("MM/dd/yyyy hh:mm tt")
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.VisitReason)
            </td>
            <td>
                <a class="text-decoration-none text-dark" href="@Url.Action("Details", "Visitations", new {  id = item.VisitID })">
                    Details
                </a>
                @if (User.IsInRole("Admin"))
                {
                    <a class="text-decoration-none text-dark px-3" href="@Url.Action("Edit", "Visitations", new {  id = item.VisitID })">
                        Edit
                    </a>
                    <a>
                        <button class="reschedule-button fw-bold bg-transparent border-0"
                                data-bs-toggle="modal"
                                data-bs-target="#reschedule-modal"
                                data-visit-id="@item.VisitID"
                                data-visit-name="@item.VisitID">
                            Reschedule
                        </button>
                    </a>
                }
            </td>
        </tr>
    }
    </table>
}
else
{
    <h1 class="mt-4">No visits.</h1>
}

<script>
    var deleteButtons = document.querySelectorAll('.reschedule-button');

    deleteButtons.forEach(function (button) {
        button.addEventListener('click', function () {
            var deleteMessage = document.querySelector('.reschedule-message');
            var visitName = button.getAttribute('data-visit-name');
            var visitID = document.getElementById('reschedule-visit-id');
            visitID.value = button.getAttribute('data-visit-id');
            deleteMessage.textContent = "Are you sure you want to reschedule this visit?";
        });
    });
</script>