MvcPresentation/Controllers/AdminController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using DataObjects;
using LogicLayer;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;
using MvcPresentation.Models;

namespace MvcPresentation.Controllers
{
    public class AdminController : Controller
    {
        //private ApplicationDbContext db = new ApplicationDbContext();
        private ApplicationUserManager _userManager;

        // GET: Admin
        public ActionResult Index(string searchText)
        {
            var users = new List<ApplicationUser>();

            try
            {
                _userManager = HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>();
                if (!string.IsNullOrEmpty(searchText))
                {
                    users = _userManager.Users.Where(n => n.Email.Contains(searchText)).ToList();
                }
                else
                {
                    users = _userManager.Users.OrderBy(n => n.Email).ToList();
                }
            }
            catch (Exception)
            {
                throw;
            }
            
            return View(users);
        }

        // GET: Admin/Details/5
        public ActionResult Details(string id)
        {
            if(id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            // ApplicationUser applicationUser = db.ApplicationUsers.Find(id)
            _userManager = HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>();
            ApplicationUser applicationUser = _userManager.FindById(id);

            if(applicationUser == null)
            {
                return HttpNotFound();
            }

            // get a list of roles the user has and put them into a viewbag as roles 
            // along with a list of the roles the user doesn't have as noRoles
            var usrMgr = new LogicLayer.UserManager();
            var allRoles = usrMgr.SelectAllRoles().Select(x => x.RoleID);

            var roles = _userManager.GetRoles(id);
            var noRoles = allRoles.Except(roles);

            return View(applicationUser);
        }
    }
}

MvcPresentation/Controllers/AnalyticsController.cs
using DataObjects;
using LogicLayer;
using MvcPresentation.Models;
using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Drawing;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebGrease.Css.Extensions;

namespace MvcPresentation.Controllers
{
    [Authorize(Roles = "Admin,CEO")]
    public class AnalyticsController : Controller
    {
        private MainManager _manager = MainManager.GetMainManager();
        private DonationCalculations calc = DonationCalculations.GetDonationCalculations();

        public ActionResult Dashboard()
        {
            DashboardVM dashboard;

			DateTime ThreeMonthsAgo = DateTime.Now.AddMonths(-3);
            List<Donation> threeMonthDonations = calc.MonthDonations(ThreeMonthsAgo.Month, ThreeMonthsAgo.Year);
            List<Donation> lastMonthDonations = calc.MonthDonations(ThreeMonthsAgo.AddMonths(1).Month, ThreeMonthsAgo.AddMonths(1).Year);
            List<Donation> currentDonations = calc.MonthDonations(ThreeMonthsAgo.AddMonths(2).Month, ThreeMonthsAgo.AddMonths(2).Year);

            var calculations = calc.DonationCalculate();
            try
            {
                dashboard = new DashboardVM()
                { // start
                    UserCount = calc.TotalUserCount().ToString("N0"),
                    InventoryCount = calc.TotalInventoryCount().ToString("N0"),
                    VenderCount = calc.TotalVendorCount().ToString("N0"),
                    CEO = calc.GetEmployeeByRole("CEO"),
                    Security = calc.GetEmployeeByRole("Security"),
                    DonationAmount = calculations.profit,
                    DonationCount = calculations.donations,
                    ChartData = new ChartVM()
                    {
                        Labels = new List<string> { "Last 3 months" },
                        Datasets = new List<ChartDS> {
                            new ChartDS()
                            {
                                Label = ThreeMonthsAgo.AddMonths(2).ToString("MM/yy"),
                                BGColor = "rgba(0, 128, 255, 0.4)",
                                BRColor = "rgb(0, 128, 255)",
                                Data = currentDonations.Select(d => calc.GetInt(d.Amount)).ToList()
                            },
                            new ChartDS()
                            {
                                Label = ThreeMonthsAgo.AddMonths(1).ToString("MM/yy"),
                                BGColor = "rgba(0, 255, 128, 0.4)",
                                BRColor = "rgb(0, 255, 128)",
                                Data = lastMonthDonations.Select(d => calc.GetInt(d.Amount)).ToList()
                            },
                            new ChartDS()
                            {
                                Label = ThreeMonthsAgo.ToString("MM/yy"),
                                BGColor = "rgba(255, 99, 132, 0.4)",
                                BRColor = "rgb(255, 99, 132)",
                                Data = threeMonthDonations.Select(d => calc.GetInt(d.Amount)).ToList()
                            }
                        } 
                    } 
                }; // end
            }
            catch
            {
                dashboard = new DashboardVM()
                {
                    UserCount = "???",
                    InventoryCount = "???",
                    VenderCount = "???",
                    CEO = new Employee(),
                    Security = new Employee(),
                    DonationAmount = "0",
                    DonationCount = 0,
                    ChartData = new ChartVM()
                    {
                        Labels = new List<string> { "???" },
                        Datasets = new List<ChartDS> {
                            new ChartDS()
                            {
                                Label = "???",
                                BGColor = "rgba(0,0,0,0)",
                                BRColor = "rgb(0,0,0)",
                                Data = new List<int>()
                            }
                        }
                    }
                };
            }
            return View(dashboard);
		}
			
        /// <summary>
        /// Creator: Jared Harvey
        /// Created: 03/21/2024
        /// Summary: Returns a view containing the list of stays for this shelter
        /// Last Updated By: Jared Harvey
        /// Last Updated: 03/21/2024
        /// What Was Changed: Initial Creation
        /// </summary>
        public ActionResult Stays() {
            List<StayVM> stays = new List<StayVM>();
            try {
                stays = _manager.StayManager.GetAllStaysForShelter("Test Homeless Shelter");
                PopulateStayDropDowns();
                return View(stays);
            } catch (Exception) {
                throw;
            }
        }

        private void PopulateStayDropDowns() {
            try {
                ViewBag.ClientList = _manager.UserManager.GetAllClients().Select(x => x.UserID);
                ViewBag.RoomList = _manager.RoomManager.GetRoomsByShelterID("Test Homeless Shelter").Select(x => x.RoomID);
            } catch (Exception) {
                ViewBag.ClientList = new List<string>();
                ViewBag.RoomList = new List<string>();
            }
        }

        public ActionResult CreateStay() {
            PopulateStayDropDowns();
            return View();
        }

        // POST: Analytics/Create
        [HttpPost]
        public ActionResult CreateStay(Stay inputStay) {
            try {
                if(ModelState.IsValid) {
                    _manager.StayManager.AddStay(inputStay.ClientID, inputStay.RoomID);
                }
                return RedirectToAction("Stays");
            } catch {
                PopulateStayDropDowns();
                return View(inputStay);
            }
        }

        /// <summary>
        /// Creator: Jared Harvey
        /// Created: 03/22/2024
        /// Summary: Returns the EditStay view with fields populated
        /// Last Updated By: Jared Harvey
        /// Last Updated: 03/22/2024
        /// What Was Changed: Initial Creation
        /// </summary>
        public ActionResult EditStay(int stayID) {
            Stay stay;
            try {
                stay = _manager.StayManager.GetStay(stayID);
                Session["oldStay"] = stay;
            } catch (Exception) {
                throw;
            }
            PopulateStayDropDowns();
            return View(stay);
        }

        /// <summary>
        /// Creator: Jared Harvey
        /// Created: 03/22/2024
        /// Summary: Post request that updates record in database
        /// Last Updated By: Jared Harvey
        /// Last Updated: 03/22/2024
        /// What Was Changed: Initial Creation
        /// </summary>
        [HttpPost]
        public ActionResult EditStay(Stay inputStay) {
            try {
                if (ModelState.IsValid) {
                    Stay oldStay = _manager.StayManager.GetStay(inputStay.StayID);
                    _manager.StayManager.EditStay((Stay)Session["oldStay"], inputStay);
                }
                return RedirectToAction("Stays");
            } catch {
                PopulateStayDropDowns();
                return View(inputStay);
            }
        }

        /// <summary>
        /// Creator: Jared Harvey
        /// Created: 03/29/2024
        /// Summary: Get method for delete stay
        /// Last Updated By: Jared Harvey
        /// Last Updated: 03/29/2024
        /// What Was Changed: Initial Creation
        /// </summary>
        public ActionResult DeleteStay(int stayID) {
            Stay stay;
            try {
                stay = _manager.StayManager.GetStay(stayID);
            } catch (Exception) {
                throw;
            }
            return View(stay);
        }

        /// <summary>
        /// Creator: Jared Harvey
        /// Created: 03/29/2024
        /// Summary: Post method for delete stay
        /// Last Updated By: Jared Harvey
        /// Last Updated: 03/29/2024
        /// What Was Changed: Initial Creation
        /// </summary>
        [HttpPost]
        public ActionResult DeleteStay(string stayID) {
            try {
                _manager.StayManager.RemoveStay(Convert.ToInt32(stayID));
                return RedirectToAction("Stays");
            } catch(Exception) {
                throw;
            }
        }

        /// <summary>
        /// Creator: Jared Harvey
        /// Created: 03/21/2024
        /// Summary: Returns a view containing the list of rooms for this shelter
        /// Last Updated By: Jared Harvey
        /// Last Updated: 03/21/2024
        /// What Was Changed: Initial Creation
        /// </summary>
        public ActionResult Rooms() {
            List<RoomVM> rooms = new List<RoomVM>();
            try {
                rooms = _manager.RoomManager.GetRoomsByShelterID("Test Homeless Shelter");
                return View(rooms);
            } catch (Exception) {
                throw;
            }
        }

        /// <summary>
        /// Creator: Jared Harvey
        /// Created: 03/29/2024
        /// Summary: Get method for create room
        /// Last Updated By: Jared Harvey
        /// Last Updated: 03/29/2024
        /// What Was Changed: Initial Creation
        /// </summary>
        public ActionResult CreateRoom() {
            try {
                ViewBag.statusList = _manager.RoomManager.GetRoomStatusForDropDown();
            } catch (Exception) {

                throw;
            }
            return View();
        }

        /// <summary>
        /// Creator: Jared Harvey
        /// Created: 03/29/2024
        /// Summary: Post method for create room
        /// Last Updated By: Jared Harvey
        /// Last Updated: 03/29/2024

MvcPresentation/Controllers/DonationsController.cs
using DataObjects;
using LogicLayer;
using System;
using System.Collections.Generic;
using MvcPresentation.Models;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.UI.WebControls;
using System.ComponentModel;
using Antlr.Runtime.Misc;
using Microsoft.Ajax.Utilities;

namespace MvcPresentation.Controllers
{
    public class DonationsController : Controller
    {
        private MainManager _manager = MainManager.GetMainManager();
        DonationManager donationManager = new DonationManager();

        // GET: Donations
        public ActionResult Index()
        {
            List<Donation> allDonations = new List<Donation>();

            try
            {
                allDonations = _manager.DonationManager.GetDonations();
            }
            catch 
            {
                throw;
            }

            return View(allDonations);
        }

        // GET: Donations/Details/5
        public ActionResult Details(int id)
        {
            Donation donation = new Donation();
            try
            {
                donation = _manager.DonationManager.GetDonations().FirstOrDefault(d => d.DonationID == id);
            }
            catch (Exception)
            {

                throw;
            }
            return View(donation);
        }

        private void dropdowns()
        {
            ViewBag.DonationTypes = _manager.DonationManager.GetDonationsType().Select(donation => donation.TypeName).ToList();
        }

        // GET: Donations/Create
        [Authorize]
        public ActionResult Create()
        {
            dropdowns();
            return View();
        }

        // POST: Donations/Create
        [Authorize]
        [HttpPost]
        public ActionResult Create(Models.DonationVM donationvm)
        {
            try
            {
                if(donationvm.DonationName.IsNullOrWhiteSpace())
                {
                    donationvm.DonationName = "Anonymous";
                }

                DonationType donationType = _manager.DonationManager.GetDonationsType()
                                    .FirstOrDefault(d => d.TypeName == donationvm.donationType);

                if(donationType != null)
                {
                    Donation donation = new Donation()
                    {
                        DonationTypeID = donationType.DonationTypeID,
                        DonationName = donationvm.DonationName,
                        Amount = donationvm.Amount,
                        DonationDate = DateTime.Now,
                        Active = true
                    };

                    _manager.DonationManager.CreateDonation(donation);
                    return RedirectToAction("Index");
                }
                else
                {
                    return View("Error");
                }
            }
            catch
            {
                return View("Error");
            }
        }

        // GET: Donations/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: Donations/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, Donation donation)
        {
            try
            {
                if (ModelState.IsValid)
                {
                     donation = (Donation)Session["oldDonation"];
                    _manager.DonationManager.UpdateDonation(donation);
                }

                return RedirectToAction("Index");
            }
            catch
            {
                return View(donation);
            }
        }
    }
}

MvcPresentation/Views/Analytics/CreateRoom.cshtml
@model DataObjects.Room

@{
    ViewBag.Title = "Create Room";
    IEnumerable<string> statusList = ViewBag.statusList;
}

<div class="container-md">

    @if (ViewBag.Error != null) {
        <div class="alert alert-warning" role="alert">
            @ViewBag.Error
        </div>
    }

    <h2>Create Room</h2>

    @using (Html.BeginForm("CreateRoom", "Analytics", FormMethod.Post)) {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            <h4>Room</h4>

            @* Room Number - make sure that room number doesn't already exist for the shelter *@
            <div class="form-group">
                @Html.LabelFor(model => model.RoomNumber, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.RoomNumber, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.RoomNumber, "", new { @class = "text-danger" })
                </div>
            </div>

            @* Status Dropdown *@
            <div class="form-group">
                @Html.LabelFor(model => model.Status, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownListFor(model => model.Status, new SelectList(statusList), "Choose a status:", new { @class = "form-control mb-2" })
                    @Html.ValidationMessageFor(model => model.Status, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Create" class="btn btn-primary" />
                </div>
            </div>
        </div>
    }

    <div>
        @Html.ActionLink("Back to List", "Index")
    </div>
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

MvcPresentation/Views/Analytics/CreateStay.cshtml
@model DataObjects.Stay

@{
    ViewBag.Title = "Create Stay";
    IEnumerable<string> clientList = ViewBag.ClientList;
    IEnumerable<int> roomList = ViewBag.RoomList;
}

<h2>Create Stay</h2>


@using (Html.BeginForm("CreateStay", "Analytics", FormMethod.Post)) {
    @Html.AntiForgeryToken()

<div class="form-horizontal">
    <h4>Stay</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.ClientID, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownListFor(model => model.ClientID, new SelectList(clientList), "Choose a client:", new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.ClientID, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.RoomID, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownListFor(model => model.RoomID, new SelectList(roomList), "Choose a room:", new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.RoomID, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.InDate, htmlAttributes: new { @class = "control-label col-md-2" })
        <div id="inDate"
             class="input-group date"
             data-date-format="mm-dd-yyyy"
             style="width: fit-content;">
            <div class="col-md-10">
                @Html.EditorFor(model => model.InDate, new { htmlAttributes = new { @class = "form-control", name = "inDate", type = "text", @readonly = "readonly" } })
                @Html.ValidationMessageFor(model => model.InDate, "", new { @class = "text-danger" })
            </div>
            <span class="input-group-addon">
                <i class="glyphicon glyphicon-calendar"></i>
            </span>
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.OutDate, htmlAttributes: new { @class = "control-label col-md-2" })
        <div id="outDate"
             class="input-group date"
             data-date-format="mm-dd-yyyy"
             style="width: fit-content;">
            <div class="col-md-10">
                @Html.EditorFor(model => model.OutDate, new { htmlAttributes = new { @class = "form-control", name = "outDate", type = "text", @readonly = "readonly" } })
                @Html.ValidationMessageFor(model => model.OutDate, "", new { @class = "text-danger" })
            </div>
            <span class="input-group-addon">
                <i class="glyphicon glyphicon-calendar"></i>
            </span>
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.CheckedOut, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            <div class="checkbox">
                @Html.EditorFor(model => model.CheckedOut)
                @Html.ValidationMessageFor(model => model.CheckedOut, "", new { @class = "text-danger" })
            </div>
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Create" class="btn btn-primary" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    <script>
        $(function () {
            $('#inDate').datepicker({
                autoclose: true,
                todayHighlight: true,
                todayBtn: "linked"
            });
            $('#outDate').datepicker({
                autoclose: true,
                todayHighlight: true,
                todayBtn: "linked"
            });
        });
    </script>
}

MvcPresentation/Views/Analytics/Dashboard.cshtml
@model MvcPresentation.Models.DashboardVM
<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.9.4/Chart.min.js"></script>

@{
    ViewBag.PageType = "NoHero";
}

<div class="container" style="padding-top: 5em;">
    <div class="row d-flex justify-content-between mb-4">
        <div class="col-lg-4 col-md-6 mb-4">
            <div class="card border-info">
                <div class="card-body text-center">
                    <h5 class="card-title">Users</h5>
                    <p class="card-text pt-3 fw-bold">@Model.UserCount</p>
                    @Html.ActionLink("View all Users", "Index", "Admin", new { area = "" }, new { @class = "btn btn-info" })
                </div>
            </div>
        </div>
        <div class="col-lg-4 col-md-6 mb-4">
            <div class="card border-info">
                <div class="card-body text-center">
                    <h5 class="card-title">Inventory Count</h5>
                    <p class="card-text pt-3 fw-bold">@Model.InventoryCount</p>
                    @Html.ActionLink("View Inventory", "Index", "Maintenance", new { area = "" }, new { @class = "btn btn-info" })
                </div>
            </div>
        </div>
        <div class="col-lg-4 col-md-6 mb-4">
            <div class="card border-info">
                <div class="card-body text-center">
                    <h5 class="card-title">Total Vendors</h5>
                    <p class="card-text pt-3 fw-bold">@Model.VenderCount</p>
                    <!-- Since there's no vendor view, do nothing -->
                    <a href="#" class="btn btn-info">View all Vendors</a>
                </div>
            </div>
        </div>
    </div>
    <div class="row d-flex justify-content-between">
        <div class="col-lg-8" style="height: 450px;">
            <div class="card mb-4 h-100 border-info">
                <div class="card-body text-center">
                    <div class="d-flex flex-row justify-content-around">
                        <div class="w-25 flex-grow-1">
                        </div>
                        <div class="flex-grow-1">
                            <h3 class=" card-title text-center text-nowrap">Donation Analytics</h3>
                        </div>
                        <div class="w-25 flex-grow-1">
                            @Html.ActionLink("View Donations", "Index", "Donations", new { area = "Admin" }, new { @class = "btn btn-info float-end" })

                        </div>
                    </div>
                    <p class="fs-5">
                        Total Donations:
                        <span class="fw-bold" style="color: limegreen;">@Model.DonationAmount</span>
                        | Donation Count:
                        <span class="fw-bold" style="color: #0dcaf0;">@Model.DonationCount</span>
                    </p>
                    <div class="card chart-container" style="height: 80%;">
                        <canvas id="chart" style="height: 100%; border: none"></canvas>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-lg-4" style="height: 450px;">
            <div class="card h-100 border-info">
                <div class="card-body text-center">
                    <h5 class="card-title">Company Owner Contact</h5>
                </div>
                <div class="card mx-5 rounded-4" style="height: 150px; border: 2px solid #0dcaf0">
                    <div class="card-body text-center">
                        <h5 class="card-title fw-bolder">CEO</h5>
                        <p class="card-text fw-bold">
                            Email: @Model.CEO.UserID <br>
                            Phone Number: @Model.CEO.PhoneNumber <br>
                            Roles: @Model.CEO.RoleDisplay.Split(',')[0]...
                        </p>
                    </div>
                </div>
                <div class="card m-5 rounded-4" style="height: 150px; border: 2px solid #0dcaf0">
                    <div class="card-body text-center">
                        <h5 class="card-title fw-bolder">Security</h5>
                        <p class="card-text fw-bold">
                            Email: @Model.Security.UserID <br>
                            Phone Number: @Model.Security.PhoneNumber <br>
                            Roles: @Model.Security.RoleDisplay.Split(',')[0]...
                        </p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<div style="margin-bottom: 14vh;" />

<script>
    const chart = document.getElementById("chart").getContext('2d');
    const chartData = @Html.Raw(Json.Encode(Model.ChartData));

    new Chart(chart, {
        type: 'line',
        data: {
            labels: chartData.Labels,
            datasets: chartData.Datasets.map(ds => {
                return {
                    label: ds.Label,
                    backgroundColor: ds.BGColor,
                    borderColor: ds.BRColor,
                    data: ds.Data
                };
            })
        },
    });
</script>

MvcPresentation/Views/Analytics/EditStay.cshtml
@model DataObjects.Stay

@{
    ViewBag.Title = "Edit Stay";
    IEnumerable<string> clientList = ViewBag.ClientList;
    IEnumerable<int> roomList = ViewBag.RoomList;
}

<h2>Edit Stay</h2>


@using (Html.BeginForm("EditStay", "Analytics", FormMethod.Post)) {
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Stay</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.StayID)

        <div class="form-group">
            @Html.LabelFor(model => model.ClientID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.ClientID, new SelectList(clientList), "Choose a client:", new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ClientID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.RoomID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.RoomID, new SelectList(roomList), "Choose a room:", new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.RoomID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.InDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div id="inDate"
                 class="input-group date"
                 data-date-format="mm-dd-yyyy"
                 style="width: fit-content;">
                <div class="col-md-10">
                    @Html.EditorFor(model => model.InDate, new { htmlAttributes = new { @class = "form-control", name = "inDate", type = "text", @readonly = "readonly" } })
                    @Html.ValidationMessageFor(model => model.InDate, "", new { @class = "text-danger" })
                </div>
                <span class="input-group-addon">
                    <i class="glyphicon glyphicon-calendar"></i>
                </span>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.OutDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div id="outDate"
                 class="input-group date"
                 data-date-format="mm-dd-yyyy"
                 style="width: fit-content;">
                <div class="col-md-10">
                    @Html.EditorFor(model => model.OutDate, new { htmlAttributes = new { @class = "form-control", name = "outDate", type = "text", @readonly = "readonly" } })
                    @Html.ValidationMessageFor(model => model.OutDate, "", new { @class = "text-danger" })
                </div>
                <span class="input-group-addon">
                    <i class="glyphicon glyphicon-calendar"></i>
                </span>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CheckedOut, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.CheckedOut)
                    @Html.ValidationMessageFor(model => model.CheckedOut, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Stays")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    <script>
        $(function () {
            $('#inDate').datepicker({
                autoclose: true,
                todayHighlight: true,
                todayBtn: "linked"
            });
            $('#outDate').datepicker({
                autoclose: true,
                todayHighlight: true,
                todayBtn: "linked"
            });
        });
    </script>
}