MvcPresentation/Controllers/EventsController.cs
using DataObjects;
using LogicLayer;
using Microsoft.AspNet.Identity;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.UI.WebControls;

namespace MvcPresentation.Controllers
{
    public class EventsController : Controller
    {
        private MainManager _manager = MainManager.GetMainManager();

        ///</summary>
        ///Creator:            Matthew Baccam
        ///Created:            04/26/2024
        ///Summary:            Created the index
        ///Last Updated By:    Matthew Baccam
        ///Last Updated:       04/26/2024
        ///What Was Changed:   Initial creation
        ///</summary>
        // GET: Events
        public ActionResult Index()
        {
            List<EventVM> events = new List<EventVM>();
            List<Models.EventVM> eventVMs = new List<Models.EventVM>();
            try
            {
                events = _manager.EventManager.getAllEvents();
                events.ForEach(eventSelected =>
                {
                    eventVMs.Add(new Models.EventVM()
                    {
                        id = eventSelected.EventID.ToString(),
                        title = eventSelected.EventName,
                        start = eventSelected.StartTime.ToString("yyyy-MM-dd"),
                        end = eventSelected.EndTime.ToString("yyyy-MM-dd"),
                        url = $"/Events/Details?id={eventSelected.EventID}"//This will be linked to the details page
                    });
                });
            }
            catch
            {
                throw;
            }
            return View(eventVMs);
        }

        ///</summary>
        ///Creator:            Matthew Baccam
        ///Created:            04/26/2024
        ///Summary:            Created details for an event
        ///Last Updated By:    Matthew Baccam
        ///Last Updated:       04/26/2024
        ///What Was Changed:   Initial creation
        ///</summary>
        // GET: Events/Details/5
        public ActionResult Details(string id)
        {
            EventVM currentEvent = new EventVM();
            try
            {
                currentEvent = _manager.EventManager.SelectEventVMByID(int.Parse(id));
            }
            catch (Exception)
            {
                return RedirectToAction("Error");
            }
            return View(currentEvent);
        }

        // GET: Events/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Events/Create
        [HttpPost]
        public ActionResult Create(Event currentEvent)
        {
            try
            {
                _manager.EventManager.CreateEvent(currentEvent);
                return RedirectToAction("Index");
            }
            catch(Exception)
            {
                ModelState.AddModelError("", "An error occurred while creating the event. Please try again.");
                return View(currentEvent);
            }
        }

        // GET: Events/Edit/5
        public ActionResult Edit(int id)
        {
            Event currentEvent = null;

            try
            {
                currentEvent = _manager.EventManager.SelectEventByEventID(id);
                Session["oldEvent"] = currentEvent;
            }
            catch
            {
                return RedirectToAction("Error");
            }
            return View(currentEvent);
        }

        // POST: Events/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, Event currentEvent)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    // guess we don't need the old event? lmao
                    Event oldEvent = (Event)Session["oldEvent"];
                    _manager.EventManager.UpdateEvent(currentEvent);
                }
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // POST: Events/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, Event eventToDelete)
        {
            //doesnt work lmao
            try
            {
                var foundEvent = _manager.EventManager.SelectAllEvents().FirstOrDefault(x => x.EventID == id);

                if (foundEvent == null)
                {
                    return View("Error");
                }
                else
                {
                    EventVM evVM = new EventVM();
                    evVM.EventID = foundEvent.EventID;
                    _manager.EventManager.DeleteEvent(evVM);
                    return RedirectToAction("Index");
                }
            }
            catch
            {
                return View();
            }
            return View();
        }
    }
}

MvcPresentation/Controllers/FundraisingController.cs
using DataObjects;
using LogicLayer;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MvcPresentation.Controllers
{
    public class FundraisingController : Controller
    {
        private MainManager _manager = MainManager.GetMainManager();
        // GET: FundraisingEvents
        public ActionResult Index()
        {
            List<FundraisingEvent> events = new List<FundraisingEvent>();
            try
            {
                events = _manager.FundraisingEventManager.GetFundraisingEvents();
            }
            catch
            {
                throw;
            }
            return View(events);
        }

        // GET: FundraisingEvents/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: FundraisingEvents/Create
        [HttpPost]
        public ActionResult Create(FundraisingEvent fundraiser)
        {
            try
            {
                _manager.FundraisingEventManager.CreateFundraisingEvent(fundraiser);
                return RedirectToAction("Index");
            }
            catch (Exception)
            {
                ModelState.AddModelError("", "An error occurred while creating the fundraiser. Please try again.");
                return View(fundraiser);
            }
        }
    }
}

MvcPresentation/Controllers/SecurityController.cs
using DataObjects;
using LogicLayer;
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MvcPresentation.Controllers
{
    public class SecurityController : Controller
    {
        private MainManager _manager = MainManager.GetMainManager();

        // GET: Security
        public ActionResult Index()
        {
            List<Incident> incidents = new List<Incident>();
            try
            {
                var email = User.Identity.GetUserName();
                if(User.IsInRole("Admin"))
                {
                    incidents = _manager.IncidentManager.SelectAllIncidents();
                }
                else
                {
                    incidents = _manager.IncidentManager.SelectAllIncidents().Where(x => x.reportedBy == email).ToList();
                }
            }
            catch
            {
                throw;
            }
            return View(incidents);
        }

        // GET: Security/Details/5
        public ActionResult Details(int incidentID)
        {
            Incident incident = new Incident();
            try
            {
                incident = _manager.IncidentManager.SelectAllIncidents().FirstOrDefault(i => i.incidentID == incidentID);
            }
            catch
            {
                throw;
            }
            return View(incident);
        }

        // GET: Security/Create
        public ActionResult Create()
        {
            return View();
        }

        private void dropdowns() 
        {
            ViewBag.IncidentStatuses =  new List<string> { "Processing", "Handled" };
        }

        // POST: Security/Create
        [HttpPost]
        public ActionResult Create(Incident incident)
        {
            try
            {
                incident.incidentStatus = "Unviewed";
                incident.feedBack = "Unviewed";
                incident.reportedBy = User.Identity.GetUserName();
                _manager.IncidentManager.AddIncident(incident.description, 
                    incident.reported, incident.reportedBy, incident.severity);
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Security/Edit/5
        public ActionResult Edit(int id)
        {
            Incident incident = new Incident();
            try
            {
                incident = _manager.IncidentManager.SelectAllIncidents().FirstOrDefault(x => x.incidentID == id);
            }
            catch (Exception)
            {
                throw;
            }
            dropdowns();
            return View(incident);
        }

        // POST: Security/Edit/5
        [HttpPost]
        public ActionResult Edit(Incident incident)
        {
            try
            {
                if(ModelState.IsValid)
                {
                    //incident.incidentStatus = "Unviewed";
                    //incident.reportedBy = User.Identity.GetUserName();
                    // updateIncident
                }
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

MvcPresentation/Views/Shared/_Layout.cshtml
@*
Creator: Liam Easton
Created: 3/10/2024
Summary: Creation of the layout page
Last Updated By: Ethan McElree
Last Updated: 3/27/2024
What Was Changed: Removed align-bottom from footer.  Align-bottom interfered with forms bigger than window size.
Last Updated By: Matthew Baccam
Last Updated: 04/11/2024
What Was Changed: Added bootstraps js tag, created visibility options based on the user viewing
*@
@*@model MvcPresentation.Models.AddPhoneNumberViewModel*@
@using Microsoft.AspNet.Identity
@{
ViewBag.Dropdown = "Phone Number";
}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Homes for the Homeless</title>
    <script src="https://www.google.com/recaptcha/api.js" async defer></script>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <script src='https://cdn.jsdelivr.net/npm/fullcalendar@6.1.11/index.global.min.js'></script>
</head>
<body class="text-light bg-radial-gradient">
    <div class="sticky-top">
        <nav class="navbar navbar-expand-lg px-4">
            <a href="@Url.Action("Index", "Home")" class="d-inline-flex link-body-emphasis text-decoration-none m-lg-2">
                <img src="~/Images/circlelogo.png" style="height: 32px" alt="...">
            </a>
            <a class="navbar-brand" href="@Url.Action("Index", "Home")">Homes For The Homeless</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0 w-100 mx-3">
                    @if (!Request.IsAuthenticated)
                    {
                        <li class="nav-item">@Html.ActionLink("Volunteer", "VolunteerApplication", "Applications", new { area = "" }, new { @class = "nav-link" })</li>
                        <li class="nav-item">@Html.ActionLink("Donations", "Index", "Donations", new { area = "" }, new { @class = "nav-link" })</li>
                        <li class="nav-item">@Html.ActionLink("About Us", "About", "Home", new { area = "" }, new { @class = "nav-link" })</li>
                    }

                    @if (Request.IsAuthenticated)
                    {
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                Events
                            </a>
                            <ul class="dropdown-menu dropdown-menu-item">
                                <li class="nav-item">@Html.ActionLink("All Events", "Index", "Events", new { area = "" }, new { @class = "nav-link" })</li>
                                <li class="nav-item">@Html.ActionLink("Fundraising Events", "Index", "Fundraising", new { area = "" }, new { @class = "nav-link" })</li>
                            </ul>
                        </li>

                        <li class="nav-item">@Html.ActionLink("Appointments", "Index", "Appointments", new { area = "" }, new { @class = "nav-link" })</li>
                        if (User.IsInRole("Admin"))
                        {
                            <li class="nav-item">@Html.ActionLink("Orders", "Index", "Transportation", new { area = "" }, new { @class = "nav-link" })</li>
                            <li class="nav-item">@Html.ActionLink("Analytics", "Dashboard", "Analytics", new { area = "" }, new { @class = "nav-link" })</li>
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                    Administration
                                </a>
                                
                                <ul class="dropdown-menu dropdown-menu-item">
                                    <li class="nav-item">@Html.ActionLink("Admin", "Index", "Admin", new { area = "" }, new { @class = "nav-link" })</li>
                                    <li class="nav-item">@Html.ActionLink("Volunteers", "Index", "Volunteering", new { area = "" }, new { @class = "nav-link" })</li>
                                    <li class="nav-item">@Html.ActionLink("Incidents", "Index", "Security", new { area = "" }, new { @class = "nav-link" })</li>
                                    <li class="nav-item">@Html.ActionLink("Visitations", "Index", "Visitations", new { area = "" }, new { @class = "nav-link" })</li>
                                    <li class="nav-item">@Html.ActionLink("Maintenance", "Index", "Maintenance", new { area = "" }, new { @class = "nav-link" })</li>
                                </ul>
                            </li>
                        }
                    }
            </ul>
            @Html.Partial("_LoginPartial")
        </div>
    </nav>
</div>

<div>
    <div class="row mx-5">
        <div class="row justify-content-center">
            <div class="col">
                @if (@ViewBag.PageType != "NoHero")
                {
                    <br />
                    <h1 class="text-center fw-bold mt-2">
                        @*if the title doesn't match what I want for the header*@

                        @if (@ViewBag.Hero != null)
                        {
                            @ViewBag.Hero
                        }
                        else
                        {
                            @ViewBag.Title
                        }
                    </h1>
                    <hr class="hr-underline">
                    <br />
                }
            </div>
        </div>
    </div>
    @{
        if (ViewBag.Content == "NoContent")
        {
            @RenderBody()
        }
        else
        {
            <div class="content text-dark px-5">
                @RenderBody()
            </div>
        }

    }
</div>

@RenderSection("scripts", required: false)
<script src="https://cdn.jsdelivr.net/npm/&#64popperjs/core@2.11.6/dist/umd/popper.min.js" integrity="sha384-oBqDVmMz9ATKxIep9tiCxS/Z9fNfEXiDAYTujMAeBAsjFuCZSmKbSSUnQlmh/jp3" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.min.js" integrity="sha384-cuYeSxntonz0PPNlHhBs68uyIAVpIIOZZ5JqeqvYYIcEL727kskC66kF92t6Xl2V" crossorigin="anonymous"></script>

<footer class="text-center">
    <p>&copy; @DateTime.Now.Year - Homes for the Homeless</p>
</footer>
</body>
</html>